Development/3/update parking area by id and parkingareaupdaterequest
Rapter1990/parkinglot pull request #16
Opened 2024-02-17 20:16 UTC by artfulCoder98

2024-02-17 20:43 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +class ParkingAreaUpdateServiceImplTest extends BaseServiceTest {
ParkingAreaUpdateServiceImpl'de

```
private final ParkingAreaEntityToParkingAreaDomainModel parkingAreaEntityToParkingAreaDomainModel =
            ParkingAreaEntityToParkingAreaDomainModel.initialize();

```
Mapper tanımlanıp buradaki testler ona göre revize edilmeli.

2024-02-17 20:43 UTC, Rapter1990 commented on src/main/resources/application.yml
> +    password: ${DATABASE_PASSWORD:yusuf123}
Burayı eski haline getirelim.

`password: ${DATABASE_PASSWORD:password}`

2024-02-17 20:43 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/controller/ParkingAreaController.java
>  public class ParkingAreaController {
Buraki create ve delete methodları neden sildin.

Git pull alıp bu kısmı revize edelim.

2024-02-17 21:17 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        mockParkingAreaEntity.setId(mockUpdateEntityId);
ParkingAreaEntity'de Builder tanımlı `setId` ve `setCapacity`'yi builder ile yapalım.

2024-02-17 21:19 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +
2 satır boşluk var. 1 tanesini silelim.

2024-02-17 21:19 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +        Mockito.verify(parkingAreaRepository,Mockito.times(0)).save(Mockito.any(ParkingAreaEntity.class));
Buradan sonra boşluk ekleyelim.

2024-02-17 21:19 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +
Buradaki gereksiz boşlukları silelim. 1 tane yeterli olur.

2024-02-17 22:23 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +        final ParkingAreaEntity parkingAreaFromDB = parkingAreaRepository
`parkingAreaFromDB `böyle bir isimlendirme olmamalı. `existiingParkingArea `desek daha doğru olur.

2024-02-17 22:23 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        final ParkingArea mockParkingAreaDomainModel = parkingAreaEntityToParkingAreaDomainModelMapper
Controller mapper olmadığından burayı sileceğiz.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +    }
Buradan sonra boşluk koyalım

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +                .parkingAreaUpdateByCapacity(mockParkingAreaId,mockUpdateRequest);
Buradan sonra boşluk koyalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
Buradaki gereksiz boşlukları silelim.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +
Buradaki gereksiz boşlukları silelim.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        ).thenThrow(new RuntimeException());
Buradaki hata mesajını revize edelim.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +                .parkingAreaUpdateByCapacity(Mockito.anyString(),Mockito.any(ParkingAreaUpdateRequest.class));
Buradan sonra boşluk koyalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //verify
Burada `// Verify` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //then
Burada `// Then` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //when
Burada `// When` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //when
Burada `// When` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //Given
Burada `// Given` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //then
Burada `// Then` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //verify
Burada `// Verify` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //Given
Burada `// Given` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +        //Verify
Burada `// Verify` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +        //Given
Burada `// Given` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +        //when
Burada `// When` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +        //Then
Burada `// Then` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +        //Verify
Burada `// Verify` şeklinde yazalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +        Mockito.verify(parkingAreaRepository,Mockito.times(1)).save(mockParkingAreaEntity);
Buradan sonra boşluk koyalım.

2024-02-18 15:57 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +}
Buradan sonra boşluk koyalım

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/exception/GlobalExceptionHandler.java
> +    }
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorResponse);
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/exception/parkingarea/ParkingAreaCapacityCanNotBeNull.java
> +    }
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/model/mapper/parking_area/ParkingAreaDomainModelToParkingAreaEntityMapper.java
> +    }
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/model/mapper/parking_area/ParkingAreaDomainModelToParkingAreaEntityMapper.java
> +public interface ParkingAreaDomainModelToParkingAreaEntityMapper extends BaseMapper<ParkingArea, ParkingAreaEntity> {
`ParkingAreaToParkingAreaEntityMapper `olarak revize edelim.

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/model/mapper/parking_area/ParkingAreaEntityToParkingAreaDomainModel.java
> +public interface ParkingAreaEntityToParkingAreaDomainModel extends BaseMapper<ParkingAreaEntity,ParkingArea> {
`ParkingAreaEntityToParkingArea` olarak revize edelim.

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +public class ParkingAreaUpdateServiceImpl implements ParkingAreaUpdateService {
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +    ) {
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/ParkingAreaUpdateRequestBuilder.java
> +    public ParkingAreaUpdateRequest build(){return super.build();}
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/ParkingAreaUpdateRequestBuilder.java
> +public class ParkingAreaUpdateRequestBuilder extends BaseBuilder<ParkingAreaUpdateRequest>{
Buradan sonra boşluk koyalım.

2024-02-18 20:34 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkingAreaControllerTest.java
> +
Buradaki gereksiz boşlukları silelim.

2024-02-18 20:34 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +    void givenEmptyParkingAreaUpdate_whenUpdateParkingArea_thenThrowParkingAreaNotFoundException(){
Burada `ParkingAreaNotFoundException` göre test method var. `ParkingAreaCapacityCanNotBeNull` göre test yazılmamış. Onu yazalım.

2024-02-18 20:40 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/exception/parkingarea/ParkingAreaCapacityCanNotBeNull.java
> +public class ParkingAreaCapacityCanNotBeNull extends RuntimeException {
ParkingAreaCapacityCanNotBeNullException olarak revise edelim.

2024-02-18 20:55 UTC, Rapter1990 commented on pom.xml
> +		<dependency>
Pom.xml'de yeni dependency eklemene gerek yok. Origin/main'den pull sonra merge alacaksın

2024-02-20 09:12 UTC, artfulCoder98 commented on src/main/java/com/project/parkinglot/controller/ParkingAreaController.java
> +        return CustomResponse.ok("Parking area with id " + parkingArea.getId() + " is updated");
bu kısım frontend'in daha kolay işlemesi için sadece id değerrini dönmesi daha mı uygun olur @mehmetseymusyuzen @Rapter1990 @moaydogdu @anilhazar

2024-02-20 12:10 UTC, moaydogdu requested changes

2024-02-20 12:10 UTC, moaydogdu commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +        final ParkingArea mockParkingArea =
Değişken isimlendirmesinde mock kullanmak çok doğru değil, burada gerçekten bir servis çağrımı yapıyoruz ve bir response dönüyor. parkingAreaResponse şeklinde isimlendirilebilir.

2024-02-20 12:10 UTC, moaydogdu commented on src/test/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImplTest.java
> +    }
Bu teste gerek yok, zaten bu kontrol request nesnesi içerisinde yapılıyor. Böyle bir isteğin servise düşmemesi gerekiyor zaten.

2024-02-20 14:47 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +    }
`checkParkingAreaRequestCapacity ` methodunu silelim.

2024-02-21 12:54 UTC, moaydogdu requested changes
Lütfen değişiklikleri yaparsan, conversation'ları resolve etmeyi unutma.

2024-02-21 12:54 UTC, moaydogdu commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +        final ParkingAreaEntity existingParkingArea = parkingAreaRepository
`existingParkingArea` yerine `parkingAreaEntityToBeUpdate` gibi bir isimlendirme çok daha açıklayıcı olabilir.

2024-02-21 12:54 UTC, moaydogdu commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +public class ParkingAreaUpdateServiceImpl implements ParkingAreaUpdateService {
Implementation classlarını public tanımlamak yerine package private olarak tanımlamak (default) çok daha doğru bir yaklaşım olabilir.

Böylelikle interface dışındaki implementasyonlar doğrudan çağrılamazlar.

2024-02-21 12:54 UTC, moaydogdu commented on src/test/java/com/project/parkinglot/builder/ParkingAreaEntityBuilder.java
> +    public ParkingAreaEntityBuilder witId(
`witId` yerine `withId` şeklinde doğru bir isimlendirme yapalım.

2024-02-21 12:54 UTC, moaydogdu commented on src/test/java/com/project/parkinglot/builder/ParkingAreaUpdateRequestBuilder.java
> +    public ParkingAreaUpdateRequestBuilder withValidField(){
`withValidField` yerine `withValidFields` şeklinde bir isimlendirme yapalım. Böylelikle ilerleyen gelişmelerde yeni field'lar eklenirse buradaki isimlendirme ile uyumlu olur.

2024-02-21 17:23 UTC, mehmetseymusyuzen commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +public class ParkingAreaUpdateServiceImpl implements ParkingAreaUpdateService {
Katiliyorum Muhammet Abiye

2024-02-21 18:31 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +public class ParkingAreaUpdateServiceImpl implements ParkingAreaUpdateService {
`class ParkingAreaUpdateServiceImpl implements ParkingAreaUpdateService {` olarak revize edelim

2024-02-21 18:32 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleParkingAreaNotFoundException(ParkingAreaCapacityCanNotBeNullException ex) {
@artfulCoder98

2024-02-21 18:32 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/ParkingAreaEntityBuilder.java
> +
@artfulCoder98

2024-02-21 18:33 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/controller/ParkingAreaController.java
> +            ){
@artfulCoder98

2024-02-21 18:33 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaUpdateServiceImpl.java
> +public class ParkingAreaUpdateServiceImpl implements ParkingAreaUpdateService {
`class ParkingAreaUpdateServiceImpl implements ParkingAreaUpdateService {` revize edelim. @artfulCoder98

2024-02-21 19:27 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/parking_area/impl/ParkingAreaCreateServiceImpl.java
> +class ParkingAreaCreateServiceImpl implements com.project.parkinglot.service.parking_area.ParkingAreaCreateService {
`com.project.parkinglot.service.parking_area.ParkingAreaCreateService` burayı `ParkingAreaCreateService  `olarak değiştirelim

2024-02-21 20:15 UTC, mehmetseymusyuzen approved these changes
LGTM!!!

2024-02-21 20:55 UTC, anilhazar approved these changes

2024-02-22 15:23 UTC, moaydogdu approved these changes
Finally look good to me.

2024-02-22 15:41 UTC, Rapter1990 approved these changes
LGTM!

2024-02-22 15:41 UTC, merged