Development/11/assign vehicle to user
Rapter1990/parkinglot pull request #22
Opened 2024-03-02 12:59 UTC by artfulCoder98

2024-03-02 14:53 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(com.project.parkinglot.exception.parkingarea.ParkingAreaAlreadyExistException.class)
Bu kısmı ParkingAreaAlreadyExistException.class olarak tekrar revise edelim. 

`@ExceptionHandler(ParkingAreaAlreadyExistException.class)`

2024-03-02 14:53 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/model/entity/VehicleEntity.java
> +    private List<ParkEntity> parkEntities;//mapperda buraya bak
`//mapperda buraya bak` silelim

2024-03-02 14:53 UTC, Rapter1990 commented on src/main/resources/application.yml
> +    password: ${DATABASE_PASSWORD:${password}}
Bu kısmı `password: ${DATABASE_PASSWORD:password}`

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Given
`//Given` -> `// Given` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //When
`//When` -> `// When` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Verify
`//Verify` -> `// Verify` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        Mockito.verify(vehicleRepository,Mockito.times(1)).save(Mockito.any(VehicleEntity.class));
Buradan sonra 1 satır boşluk bırakalım.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        Mockito.verify(vehicleRepository,Mockito.never()).save(Mockito.any(VehicleEntity.class));
Buradan sonra 1 satır boşluk bırakalım.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //When
`//When` -> `// When` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Given
`//Given` -> `// Given` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Then
`//Then` -> `// Then` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Given
`//Given` -> `// Given` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //When
`//When` -> `// When` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Then
`//Then` -> `// Then` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Verify
`//Verify` -> `// Verify` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //Verify
`//Verify` -> `// Verify` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //Then
`//Then` -> `// Then` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //Given
`//Given` -> `// Given` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //when
`//When` -> `// When` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //Then
`//Then` -> `// Then` olarak düzeltelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(),Mockito.any(VehicleRequest.class));
Buradan sonra boşluk bırakalım.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(), Mockito.any(VehicleRequest.class));
Buradan sonra boşluk bırakalım.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(), Mockito.any(VehicleRequest.class));
Buradan sonra boşluk bırakalım.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +     private final VehicleToVehicleEntityMapper vehicleToVehicleEntityMapper =
`VehicleController` class'ın herhangi bir mapper olmadığı için buradaki mapperlar silelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //Given
`//Given` -> `// Given` olarak revise edelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //When
`//When` -> `// When` olarak revise edelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //Then
`//Then` -> `// Then` olarak revise edelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +         //Verify
`//Verify` -> `// Verify` olarak revise edelim.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/VehicleRequestBuilder.java
> +    }
Buradan sonra boşluk bırakalım.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/VehicleEntityBuilder.java
> +    }
Buradan sonra boşluk bırakalım.

2024-03-02 14:53 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +
`VehicleServiceImpl `kısmında 3 tane mapper kullanaılmış. Burada sadece 1 tanesi var. Ona göre JUnit testleri revise edelim.

2024-03-02 18:04 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(VehicleAlreadyExist.class)
278.satırdan sonra boşluk koyalım.

2024-03-02 18:04 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/model/mapper/vehicle/VehicleEntityToVehicleMapper.java
> +    }
19.satırdan sonra boşluk koyalım.

2024-03-02 18:04 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/model/mapper/vehicle/VehicleRequestToVehicleMapper.java
> +    }
18.satırdan sonra boşluk koyalım.

2024-03-02 18:04 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/vehicle/VehicleService.java
> +    );
11.satırdan sonra boşluk koyalım.

2024-03-02 18:04 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/vehicle/impl/VehicleServiceImpl.java
> +        return vehicleEntityToBePersist;
72.satırdan sonra boşluk koyalım.

2024-03-02 18:04 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/VehicleRequestBuilder.java
> +
Buradaki boşluğu silelim.

2024-03-02 18:04 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +     private final VehicleToVehicleEntityMapper vehicleToVehicleEntityMapper =
Bu kısmı düzeltelim. @artfulCoder98

2024-03-02 18:04 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +
`Assertions.assertEquals` bu kısımlardaki boşlukları silelim.

2024-03-02 18:04 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Given
@artfulCoder98 Bu kısımda herhangi bir değişiklik olmamış.

2024-03-02 18:04 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +
161.satırdaki boşluğu silelim

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(), Mockito.any(VehicleRequest.class));
@artfulCoder98 Burada herhangi bir değişiklik olmamış.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(), Mockito.any(VehicleRequest.class));
@artfulCoder98 Burada herhangi bir değişiklik olmamış.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(),Mockito.any(VehicleRequest.class));
@artfulCoder98 Burada herhangi bir değişiklik olmamış.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(),Mockito.any(VehicleRequest.class));
188. satırdan sonra boşluk bırakalım.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        final Vehicle mockVehicleToCreated = vehicleEntityToVehicleMapper.map(mockVehicleEntity);
71. satırdan sonra boşluk bırakalım.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        //Verify
@artfulCoder98 Burada herhangi bir değişiklik olmamış.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +
Mockito.verfiy kısımlarında boşlukları kaldıralım.

```
Mockito.verify()
Mockito.verify()
```

Şeklinde olsun.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        Mockito.verify(vehicleRepository,Mockito.times(1)).save(Mockito.any(VehicleEntity.class));
@artfulCoder98 Burada herhangi bir değişiklik olmamış.

2024-03-03 12:16 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        Mockito.verify(vehicleRepository,Mockito.never()).save(Mockito.any(VehicleEntity.class));
@artfulCoder98 Burada herhangi bir değişiklik olmamış.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        Mockito.verify(vehicleRepository,Mockito.times(1)).save(Mockito.any(VehicleEntity.class));
@artfulCoder98 burası düzelmemiş.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        Mockito.verify(vehicleRepository,Mockito.never()).save(Mockito.any(VehicleEntity.class));
@artfulCoder98 Burası hala düzelmemiş.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(),Mockito.any(VehicleRequest.class));
@artfulCoder98 Burası hala düzelmemiş.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(),Mockito.any(VehicleRequest.class));
@artfulCoder98 Burası hala düzelmemiş.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(), Mockito.any(VehicleRequest.class));
@artfulCoder98 Burası hala düzelmemiş.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(), Mockito.any(VehicleRequest.class));
@artfulCoder98 Burası hala düzelmemiş.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/VehicleRequestBuilder.java
> +    }
54.satırdan sonra boşluk bırakalım.

2024-03-03 13:15 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/builder/VehicleEntityBuilder.java
> +    }
Burayı

```
    private VehicleType generateRandomVehicleType(){
        Random rnd = new Random();
        int randomValue = rnd.nextInt(VehicleType.values().length);
        return VehicleType.values()[randomValue];
    }
```
şe şekilde yapalım ve bundan sonra 1 satır boşuk bırakalım.

2024-03-03 13:54 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/VehicleControllerTest.java
> +                 .assignVehicleToUser(Mockito.anyString(),Mockito.any(VehicleRequest.class));
@artfulCoder98 Burası hala düzelmemiş.

2024-03-03 13:54 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/VehicleService/VehicleServiceImplTest.java
> +        Mockito.verify(vehicleRepository,Mockito.never()).save(Mockito.any(VehicleEntity.class));
@artfulCoder98 Burası hala düzelmemiş.

2024-03-03 15:17 UTC, Rapter1990 approved these changes
LGTM!

2024-03-03 16:59 UTC, anilhazar approved these changes
LGTM

2024-03-04 18:00 UTC, mehmetseymusyuzen commented
Reviews yarin yapcagim.

2024-03-05 13:13 UTC, mehmetseymusyuzen requested changes
Bunlari gozden gecirir misin?

2024-03-05 13:13 UTC, mehmetseymusyuzen commented on src/main/java/com/project/parkinglot/exception/vehicle/VehicleAlreadyExist.java
> +
Eger burada baska bir spesifik mesaj vereceksek, bunun icin bir tane de parametreli consturctor yazman gerekiyor.

2024-03-05 13:13 UTC, mehmetseymusyuzen commented on src/main/java/com/project/parkinglot/model/dto/request/Vehicle/VehicleRequest.java
> +    private String licensePlate;
String bos veya null geldigi durumlarda nasil bir aksiyon almayi planliyorsun?

2024-03-05 16:21 UTC, artfulCoder98 commented on src/main/java/com/project/parkinglot/controller/VehicleController.java
> +    @PreAuthorize("hasAuthority('ROLE_DRIVER')")
![image](https://github.com/Rapter1990/parkinglot/assets/123752776/66e207fa-d9d7-4ebf-938a-23da45620f20)

issueda öyle diyor

2024-03-05 20:33 UTC, mehmetseymusyuzen approved these changes
LGTM!

2024-03-06 18:46 UTC, merged