PR : Issue 11 : Check in (Park User's Vehicle to Parking Area)
Rapter1990/parkinglot pull request #26
Opened 2024-03-10 20:35 UTC by Rapter1990

givenUserIdAndParkCheckInRequest_whenCheckIn_ReturnParkCheckInResponse and givenUserIdAndParkCheckInRequest_whenCheckIn_thenReturnParkCheckInResponse cannot be handled now.

To be fixed these methods

2024-03-11 21:56 UTC, mehmetseymusyuzen requested changes

2024-03-11 21:56 UTC, mehmetseymusyuzen commented on src/main/java/com/project/parkinglot/service/park/ParkService.java
> +
Abi fazla satırları siler misin?

2024-03-11 21:56 UTC, mehmetseymusyuzen commented on src/test/java/com/project/parkinglot/controller/ParkControllerTest.java
> +}
buraya bir satır bosluk ekleyebilir miyiz?

2024-03-11 21:56 UTC, mehmetseymusyuzen commented on src/test/java/com/project/parkinglot/service/park/impl/ParkServiceImplTest.java
> +        when(parkingAreaRepository.findById(parkCheckInRequest.getParkingAreaId())).thenReturn(Optional.ofNullable(existingParkingArea));
Abi sanırım bu test özelinden static import yapılmış, bir standartta bağlı olmamiz daha iyi olabileceği kanisindayim

2024-03-12 18:46 UTC, Rapter1990 commented on src/main/java/com/project/parkinglot/service/park/ParkService.java
> +
Gerekli değişikliği yaptım.

2024-03-12 18:46 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/controller/ParkControllerTest.java
> +}
Gerekli değişikliği yaptım.

2024-03-12 19:28 UTC, Rapter1990 commented on src/test/java/com/project/parkinglot/service/park/impl/ParkServiceImplTest.java
> +        when(parkingAreaRepository.findById(parkCheckInRequest.getParkingAreaId())).thenReturn(Optional.ofNullable(existingParkingArea));
Onu General Refactor kısımda yapabiliriz.

2024-03-12 21:18 UTC, mehmetseymusyuzen approved these changes
LGTM!

2024-03-14 11:44 UTC, artfulCoder98 approved these changes
LGTM:)

2024-03-14 12:58 UTC, anilhazar approved these changes
LGTM

2024-03-14 19:08 UTC, merged